# inventory/imports/constants.py

CSV_HEADERS = [
    "Vin",
    "Run Number",
    "Auction House",
    "Sale",
    "Start Time",
    "Main Description",
    "Secondary Description",
    "Title",
    "Grade",
    "MMR",
    "Odometer",
    "Engine",
    "Transmission",
    "Exterior Color",
    "Interior Color",
    "Consignor",
    "Consignor E-mail",
    "Consignor Address",
    "Notes",
]

HEADER_MAP = {
    "vin": "vin",
    "run number": "run_number",
    "auction house": "auction_house",
    "sale": "auction_sale_lane",
    "start time": "auction_start_at",
    "main description": "main_description",
    "secondary description": "secondary_description",
    "title": "title_status",
    "grade": "condition_grade",
    "mmr": "mmr",
    "odometer": "mileage",
    "engine": "engine",
    "transmission": "transmission",
    "exterior color": "exterior_color",
    "interior color": "interior_color",
    "consignor": "consignor_name",
    "consignor e-mail": "consignor_email",
    "consignor address": "consignor_address",
    "notes": "auction_notes",
}

IMPORT_UPDATE_FIELDS = [
    "stock_no",
    "year",
    "make",
    "model",
    "trim",
    "run_number",
    "auction_house",
    "auction_sale_lane",
    "auction_start_at",
    "main_description",
    "secondary_description",
    "title_status",
    "condition_grade",
    "mmr",
    "mileage",
    "engine",
    "transmission",
    "exterior_color",
    "interior_color",
    "consignor_name",
    "consignor_email",
    "consignor_address",
    "auction_notes",
]