"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers
import environ




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Initialise environ
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env") 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wxm6f$r6b$c86#5$%l1uu0os4dqfm%8p!u*%rcgsch1%8lye=8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "cars.buycon.com", 
    "localhost", 
    "127.0.0.1",
    "192.168.0.106",
    "52kht52z-8080.inc1.devtunnels.ms"
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://cars.buycon.com",
    "http://localhost:8080",
    "http://192.168.0.106:8080",
    "https://52kht52z-8080.inc1.devtunnels.ms"
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-company-id",
    "x-dealership-id",
]


CSRF_TRUSTED_ORIGINS = [
    "https://cars.buycon.com",
    "http://localhost:8080",
    "http://192.168.0.106:8080",
    "https://52kht52z-8080.inc1.devtunnels.ms"
]



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'billing',
    'inventory',
    'inspections',
    'hammer',
    'buying',
    'recon',
    'vendors',
    'dashboards',
    'notifications',
    'audit',
    'channels'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'backend.middleware.ApiFailEnvelopeMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'backend.asgi.application'
# WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'BuyCon',
        'USER': 'postgres',
        'PASSWORD': 'telco123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST Framework configuration
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'backend.exceptions.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# SimpleJWT token settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Access token valid for 15 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,             # token rotation
    'BLACKLIST_AFTER_ROTATION': True,          # Blacklist token
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,                  # Use Django's SECRET_KEY for signing
    'AUTH_HEADER_TYPES': ('Bearer',),           # Token prefix in Authorization header
    'USER_ID_FIELD': 'id',                      # The user field included in the token
    'USER_ID_CLAIM': 'user_id',                 # The key for the user ID in the token payload
}

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
REFRESH_COOKIE_NAME     = "buycon_rt"
REFRESH_COOKIE_PATH     = "/api/v1/accounts/auth/"
REFRESH_COOKIE_SECURE   = False         
REFRESH_COOKIE_SAMESITE = "Lax"       

FRONTEND_URL = env("FRONTEND_URL").strip()

# Stripe
STRIPE_API_KEY = env("STRIPE_API_KEY").strip()  # secret key, test/live per env
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET").strip()

CHECKOUT_SUCCESS_URL = env("CHECKOUT_SUCCESS_URL", default="https://app.buycon.com/billing/success").strip()
CHECKOUT_CANCEL_URL  = env("CHECKOUT_CANCEL_URL",  default="https://app.buycon.com/billing/cancel").strip()
BILLING_PORTAL_RETURN_URL = env("BILLING_PORTAL_RETURN_URL", default="https://app.buycon.com/billing/portal/return").strip()

STRIPE_PRICE_ID_BASIC = env("STRIPE_PRICE_ID_BASIC").strip()
TRIAL_DAYS_BASIC = int(env("TRIAL_DAYS_BASIC", default="14").strip())
ALLOWED_PRICE_IDS = [p.strip() for p in env.list("ALLOWED_PRICE_IDS", default=[])]

#SendGrid
SENDGRID_API_KEY = env("SENDGRID_API_KEY").strip()
EMAIL_FROM_ADDRESS = env("EMAIL_FROM_ADDRESS", default="info@buycon.com").strip()
EMAIL_FROM_NAME = env("EMAIL_FROM_NAME", default="Greg Campbell").strip()
EMAIL_SANDBOX_MODE = bool(env("EMAIL_SANDBOX_MODE", default="True").strip())

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_ROOT = 'static/'
STATIC_URL = '/static/'

MEDIA_ROOT = 'media/'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
