# Used by seeder to create per-company Trades and company-level InspectionItemTemplates.

# ---- Default Trades (company-scoped) ----
DEFAULT_TRADES = [
    {"key": "paint_body",  "label": "Paint & Body", "description": "Panels, paint, bumpers, exterior cosmetics", "order_index": 10},
    {"key": "mechanic",    "label": "Mechanic",     "description": "Fluids, driveline, electrical checks, basic ops", "order_index": 20},
    {"key": "pdr",         "label": "PDR",          "description": "Paintless dent repair", "order_index": 30},
    {"key": "upholstery",  "label": "Upholstery",   "description": "Seats, belts, headliner, panels", "order_index": 40},
    {"key": "tires",       "label": "Tires",        "description": "Tires, wheels, spare/jack", "order_index": 50},
    {"key": "auto_glass",  "label": "Auto Glass",   "description": "Glass, mirrors, defrost, sunroof", "order_index": 60},
    {"key": "detailer",    "label": "Detailer",     "description": "Interior detail, carpets", "order_index": 70},
]

# ---- Default Inspection Item Templates (company-level library) ----
DEFAULT_TEMPLATES_BY_TRADE = {
    "mechanic": [
        {"label": "Hood Release Operation"},
        {"label": "Under Car Oil Check"},
        {"label": "Engine Oil Level"},
        {"label": "Transmission Fluid Level"},
        {"label": "Anti-Freeze / Coolant Level"},
        {"label": "Dash Warning Light Cycle"},
        {"label": "Cold Start Noise / Smoke"},
        {"label": "Transmission In/Out Operation"},
        {"label": "Scan - Check Engine Light"},
        {"label": "Scan - ABS Light"},
        {"label": "Scan - Airbag Light"},
        {"label": "Scan - TPMS Light"},
        {"label": "HVAC System Operation"},
        {"label": "Audio / Radio Operation"},
        {"label": "A/C Vents Airflow"},
        {"label": "Window Operation"},
        {"label": "Door Lock Operation"},
        {"label": "Horn Operation"},
        {"label": "Dome / Map Lights"},
        {"label": "Wipers / Washers"},
        {"label": "Trunk Release"},
        {"label": "Gas Door Release"},
        {"label": "Parking Brake / E-Brake"},
        {"label": "Steering Wheel Condition"},
        {"label": "Headlights Operation"},
        {"label": "Tail Lights Operation"},
        {"label": "Exhaust System Condition"},
    ],
    "paint_body": [
        {"label": "Under-Hood Frame Rust"},
        {"label": "Under-Car / Frame Rust"},
        {"label": "Hood - Damage / Alignment"},
        {"label": "Front Bumper - Damage / Alignment"},
        {"label": "Grille - Condition"},
        {"label": "Fenders - Condition"},
        {"label": "Roof - Condition"},
        {"label": "Doors - Condition"},
        {"label": "Door Handles - Condition"},
        {"label": "Sail Panels - Condition"},
        {"label": "Quarter Panels - Condition"},
        {"label": "Gas Door - Condition"},
        {"label": "Rear Bumper - Damage / Alignment"},
        {"label": "Trunk / Latch - Operation"},
        {"label": "Body / Interior Cosmetic Review"},
    ],
    "auto_glass": [
        {"label": "External Mirrors - Condition"},
        {"label": "Rear Defrost - Operation"},
        {"label": "Sunroof - Operation / Leaks"},
        {"label": "Rear-View Mirror - Condition"},
        {"label": "Glass - Chips / Cracks"},
        {"label": "Window Tint - Condition"},
    ],
    "upholstery": [
        {"label": "Seat Operation"},
        {"label": "Seat Belts - Function"},
        {"label": "Center Console - Condition"},
        {"label": "Glove Box - Operation"},
        {"label": "Sun Visors - Condition"},
        {"label": "Headliner - Condition"},
        {"label": "Dashboard - Condition"},
        {"label": "Console Lid - Condition"},
        {"label": "Seats / Headrests - Condition"},
        {"label": "Door Panels - Condition"},
    ],
    "tires": [
        {"label": "Jack & Spare Tire Present"},
        {"label": "Wheel Caps / Lug Covers"},
        {"label": "Front Tires - Tread / Condition (LF/RF)"},
        {"label": "Rear Tires - Tread / Condition (LR/RR)"},
    ],
    "detailer": [
        {"label": "Detail - Exterior/Interior Needed"},
        {"label": "Carpets - Condition"},
    ],
}
